const
  WIDTH = 1024,
  HEIGHT = 512,
  GROUND_LINE = 160,
  CORE_LINE = 92,
  HILLS_MAX_H = (GROUND_LINE - CORE_LINE) / 2,
  HUD_H = 30;
export { WIDTH, HEIGHT, GROUND_LINE, CORE_LINE, HILLS_MAX_H, HUD_H };